### ISSUE TITLE
Upgrading Ebu-List to latest Docker image

### ISSUE THREAD

**Issue by kuipers-axon** [ebu/pi-list#103]
Hi,

I try to upgrade our current ebu-list tool to the latest version. But unfortunately if I upgrade the tool by pulling the new list_server, the web services doesn't come back. So I guess the upgrade failed. But I can't find why. 

The logs don't show any error messages except:
`list_server_1  |  failed!`

Maybe I have incompatible versions of rabbitmq or influxdb? Or is there something changed on the listening ports?

The commands I use:

- docker-compose pull list_server
- docker-compose up -d
- docker-compose logs -f --tail=300
- looks like it starts, but no web service is available.

Here is the docker-compose.yml we are using:
```
version: "3"
services:
  influxdb:
    image: influxdb:1.4.2
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb

  mongo:
    image: mongo:4.1.10
    restart: always
    volumes:
      - mongo:/data/db

  rabbitmq:
    image: pedroalvesferreira/rabbitmq-with-web-mqtt:3.7.15-management
    restart: always
    ports:
      - "10.1.0.57:5672:5672"
      - "10.1.0.57:15672:15672"
      - "10.1.0.57:15675:15675"

  list_server:
    image: ebutech/pi-list:v1.16.4
    restart: always
    ports:
      - "10.1.0.57:80:80"
    environment:
        - EBU_LIST_WEB_APP_DOMAIN=http://ebu-list.axon.nl
        - EBU_LIST_LIVE_MODE=true
    links:
      - influxdb
      - mongo
      - rabbitmq
    volumes:
      - /mnt/docker/ebu-pi-list/ebu-data:/home/

volumes:
  mongo:
  influxdb:
```

Hopefully somebody can give me a pointer what I´m doing wrong.

Thanks in advance!

Grtz,
Mark
